(()=>{
  const host=document.getElementById('productsRoot');
  if(!host||!window.ProductModel)return;
  let query='',category='all',source='all';
  const modal=document.createElement('div');
  modal.className='modal product-editor-modal';modal.id='productEditorModal';modal.setAttribute('aria-hidden','true');
  modal.innerHTML='<div class="modal-backdrop" data-close-product-editor></div><article class="modal-card product-editor-card" role="dialog" aria-modal="true"><button class="modal-close" data-close-product-editor>×</button><div id="productEditorContent"></div></article>';
  document.body.appendChild(modal);
  const content=modal.querySelector('#productEditorContent');
  let editingId=null,parentId=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const displayName=p=>p.brand?`${p.name} — ${p.brand}`:p.name;
  function filtered(){return ProductModel.all().filter(p=>{if(category!=='all'&&p.category!==category)return false;if(source==='standard'&&p.source!=='standard')return false;if(source==='custom'&&p.source==='standard')return false;if(query&&!displayName(p).toLowerCase().includes(query.toLowerCase()))return false;return true})}
  function card(p){const basis=p.nutritionBasis==='unit'?'на 1 шт':`на 100 ${p.unit}`;return `<article class="product-card"><div class="product-card-top"><div><span class="product-source ${p.source==='standard'?'standard':'mine'}">${p.source==='standard'?'Стандартный':'Мой продукт'}</span><h3>${esc(displayName(p))}</h3><small>${ProductModel.categories[p.category]}</small></div></div><div class="product-kbju"><strong>${p.nutrition.kcal} ккал</strong><span>Б ${p.nutrition.p}</span><span>Ж ${p.nutrition.f}</span><span>У ${p.nutrition.c}</span><small>${basis}</small></div><div class="product-card-actions">${p.source==='standard'?`<button class="action-btn" data-product-variant="${p.id}">Создать свой вариант</button>`:`<button class="action-btn primary" data-edit-product="${p.id}">Редактировать</button><button class="action-btn" data-archive-product="${p.id}">Удалить</button>`}</div></article>`}
  function render(focus=false){const items=filtered();host.innerHTML=`<div class="products-head"><div><p class="eyebrow">Справочник</p><h2>Продукты</h2><p>Используются в рецептах, расчётах КБЖУ и будущем списке покупок.</p></div><button class="add-recipe-btn" data-add-product>+ Добавить продукт</button></div><div class="product-tools"><div class="recipe-search"><span>⌕</span><input type="search" value="${esc(query)}" placeholder="Поиск продукта" data-product-search></div><select data-product-source><option value="all" ${source==='all'?'selected':''}>Все</option><option value="standard" ${source==='standard'?'selected':''}>Стандартные</option><option value="custom" ${source==='custom'?'selected':''}>Мои</option></select></div><div class="product-category-tabs"><button class="recipe-category-tab ${category==='all'?'active':''}" data-product-category="all">Все</button>${Object.entries(ProductModel.categories).map(([k,v])=>`<button class="recipe-category-tab ${category===k?'active':''}" data-product-category="${k}">${v}</button>`).join('')}</div><div class="recipe-library-summary">Найдено: <strong>${items.length}</strong> · Моих: <strong>${items.filter(x=>x.source!=='standard').length}</strong></div>${items.length?`<div class="products-grid">${items.map(card).join('')}</div>`:'<div class="recipe-library-empty"><strong>Ничего не найдено</strong><span>Измени поиск или фильтр.</span></div>'}`;bind();if(focus){const i=host.querySelector('[data-product-search]');i?.focus();if(i){const p=i.value.length;i.setSelectionRange?.(p,p)}}}
  function bind(){host.querySelector('[data-add-product]')?.addEventListener('click',()=>openEditor());host.querySelector('[data-product-search]')?.addEventListener('input',e=>{query=e.target.value;render(true)});host.querySelector('[data-product-source]')?.addEventListener('change',e=>{source=e.target.value;render()});host.querySelectorAll('[data-product-category]').forEach(b=>b.onclick=()=>{category=b.dataset.productCategory;render()});host.querySelectorAll('[data-product-variant]').forEach(b=>b.onclick=()=>openEditor(null,b.dataset.productVariant));host.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openEditor(b.dataset.editProduct));host.querySelectorAll('[data-archive-product]').forEach(b=>b.onclick=()=>{if(confirm('Удалить этот продукт из справочника?')){ProductModel.archive(b.dataset.archiveProduct);render()}})}
  function openEditor(id=null,parent=null,presetName=''){editingId=id;parentId=parent;const existing=id?ProductModel.get(id):parent?ProductModel.get(parent):null;const d=existing?{name:existing.name,brand:id?existing.brand:'',category:existing.category,unit:existing.unit,nutrition:{...existing.nutrition},defaultRole:existing.defaultRole}:{name:presetName,brand:'',category:'other',unit:'г',nutrition:{kcal:'',p:'',f:'',c:''},defaultRole:'fixed'};content.innerHTML=`<p class="eyebrow">${parent?'Вариант продукта':id?'Редактирование':'Новый продукт'}</p><h2>${parent?'Создать свой вариант':'Продукт'}</h2><div class="product-editor-fields"><label><span>Название *</span><input id="prdName" value="${esc(d.name)}" ${parent?'readonly':''}></label><label><span>Марка / вариант</span><input id="prdBrand" value="${esc(d.brand)}" placeholder="Например, Простоквашино"></label><label><span>Категория *</span><select id="prdCategory">${Object.entries(ProductModel.categories).map(([k,v])=>`<option value="${k}" ${d.category===k?'selected':''}>${v}</option>`).join('')}</select></label><label><span>Единица *</span><select id="prdUnit"><option value="г" ${d.unit==='г'?'selected':''}>г</option><option value="мл" ${d.unit==='мл'?'selected':''}>мл</option><option value="шт" ${d.unit==='шт'?'selected':''}>шт</option></select></label><label><span>Типовая роль</span><select id="prdRole">${Object.entries(RecipeModel?.roleLabels||{}).map(([k,v])=>`<option value="${k}" ${d.defaultRole===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="product-nutrition-editor"><strong>КБЖУ <span id="prdBasis">${d.unit==='шт'?'на 1 шт':'на 100 г/мл'}</span></strong><div><label>ккал<input id="prdKcal" type="number" step="0.1" min="0" value="${d.nutrition.kcal}"></label><label>Б<input id="prdP" type="number" step="0.1" min="0" value="${d.nutrition.p}"></label><label>Ж<input id="prdF" type="number" step="0.1" min="0" value="${d.nutrition.f}"></label><label>У<input id="prdC" type="number" step="0.1" min="0" value="${d.nutrition.c}"></label></div></div><div id="prdErrors" class="editor-errors"></div><button class="editor-save" data-save-product>Сохранить продукт</button>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');content.querySelector('#prdUnit').onchange=e=>content.querySelector('#prdBasis').textContent=e.target.value==='шт'?'на 1 шт':'на 100 г/мл';content.querySelector('[data-save-product]').onclick=save;setTimeout(()=>content.querySelector(parent?'#prdBrand':'#prdName')?.focus(),0)}
  function save(){const draft={name:content.querySelector('#prdName').value,brand:content.querySelector('#prdBrand').value,category:content.querySelector('#prdCategory').value,unit:content.querySelector('#prdUnit').value,defaultRole:content.querySelector('#prdRole').value,nutrition:{kcal:content.querySelector('#prdKcal').value,p:content.querySelector('#prdP').value,f:content.querySelector('#prdF').value,c:content.querySelector('#prdC').value},parentId};const res=ProductModel.save(draft,editingId);if(!res.ok){content.querySelector('#prdErrors').innerHTML=res.errors.map(x=>`<div>${esc(x)}</div>`).join('');return}close();render();window.dispatchEvent(new CustomEvent('foodplan:products-updated'))}
  function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');editingId=null;parentId=null}
  document.addEventListener('click',e=>{if(e.target.closest('[data-close-product-editor]'))close()});
  window.addEventListener('foodplan:add-product',e=>{window.showDishesSubsection?.('products');openEditor(null,null,e.detail?.name||'')});
  window.renderProductsLibrary=render;render();
})();